-- =============================================
-- SEED ARTISTS DATA
-- =============================================
INSERT INTO artists (id, name, slug, act, description, style, country, image_url, social, videos) VALUES
(1, 'the horrids', 'the-horrids', 'Live Act', 'The project has been created in the year 2019 in France. Radikal Moodz & Shred''er, combines the top of their imagination into a fresh style with energic basslines and grooves, all surrounded by organic textures broken by digital rhythms that create a full 3D world to travel inside, unique of its kind. A fairy tale journey with twisted sounds, off beat sequences and crazy sound design are some of their elements.', ARRAY['Darkpsy', 'Forest'], 'France', '/images/the-horrids.jpg', '{"soundcloud": "https://soundcloud.com/thehorrids", "instagram": "https://www.instagram.com/the.horrids", "facebook": "https://www.facebook.com/Thehorridspsy"}', ARRAY['https://soundcloud.com/thehorrids/sets/example-album']),

(2, 'dr fractal', 'dr-fractal', 'Live Act', 'Dr Fractal, real name Théo Santinacci, is a French psytrance artist affiliated with Transubtil Records. A musician since childhood and a former drummer in various bands, he launched the Dr Fractal project in 2013. His music blends groovy rhythms, deep atmospheres, and high-energy vibes. Notable releases include the album Smooth Lobotomy (2021) and the Red Spicy EP (2023), featuring collaborations with Karev and The Horrids. Dr Fractal has performed at international festivals, including the OZORA Festival in 2024.', ARRAY['Darkpsy', 'Forest', 'Hitech'], 'France', '/images/drfractal.jpg', '{"soundcloud": "https://soundcloud.com/theosantinacci", "facebook": "https://www.facebook.com/dr.fractal", "instagram": "https://www.instagram.com/dr.fractal_bakubai/"}', '{}'),

(3, 'Opsuruus', 'opsuruus', 'Live Act', 'Opsuruus, real name Sandro Viegas, is a psytrance artist from Oliveira de Azeméis, Portugal, signed to Transubtil Records. His album Surreal Contrast, released in April 2024, features collaborations with artists like Noctune, Karev, and The Horrids. Opsuruus has also performed at international festivals, including the Psycristrance Festival 2023 in Mexico.', ARRAY['Darkpsy', 'Forest', 'Hitech'], 'Portugal', '/images/opsuruus.jpg', '{"soundcloud": "https://soundcloud.com/opsuruus", "instagram": "https://www.instagram.com/sandro_opsuruus/", "facebook": "https://www.facebook.com/Opsuruus/"}', '{}'),

(4, 'Balku', 'balku', 'Live Set', 'André grew up in a family of various artists, including many musicians. He was first introduced to electronic music at a young age and quickly developed a connection to the darker and more psychedelic genres. A few years later, he felt the urge to create his own sound to express his ideas and emotions. At just 22 years old, he was already performing his live set at some of the top parties in his country. Balku''s sound is defined by a strong bassline, along with obscure, immersive, and electric sounds that aim to take the listener on an intense journey. He is constantly searching for power and darkness in his music. From his soul to your mind, Balku is André Varandas, Portugal.', ARRAY['Darkpsy', 'Forest', 'Hitech'], 'Portugal', '/images/balku.jpg', '{"soundcloud": "https://on.soundcloud.com/TNCQQVhzVgu6LDcST", "instagram": "https://www.instagram.com/balkumusic/profilecard/?igsh=MWFpY2NyYTk2dnIxOQ==", "facebook": "https://www.facebook.com/share/1D5G5KEBah/?mibextid=wwXIfr"}', '{}'),

(5, 'La Marquise', 'la-marquise', 'Live Set', '', ARRAY['Twilight'], 'France', '/images/lamarquise.jpg', '{"soundcloud": "https://soundcloud.com/m-t-0ryk", "instagram": "https://www.instagram.com/angelolamarquise/", "facebook": "https://www.facebook.com/DjLaMarquise"}', '{}'),

(6, 'Dj Art2Fly', 'dj-art2fly', 'Dj Set', 'Eduardo Ramírez Herrera a.k.a Art2Fly. He started as a DJ in 2010, he is originally from Tabasco based in Yucatan, Mexico. In 2020 he joins the French label Transubtil Records.', ARRAY['Twilight'], 'Mexico', '/images/art2fly.png', '{"soundcloud": "https://soundcloud.com/art2fly", "instagram": "https://www.instagram.com/djart2fly", "facebook": "https://www.facebook.com/DJArt2Fly"}', '{}'),

(7, 'Akhaba', 'akhaba', 'Dj Set / Live', 'Propagator of music & passionate about modern psychedelic music for 10 years, Antoine alias Akhaba is a DJ, producer and sound engineer from the south of France. Today, Akhaba is a DJ Producer in the broad sense. His performances adapt to the moment, to the dancefloor & knows how to seduce the most underground audiences and make his music accessible to as many people as possible. His DJ sets are dancefloor, complex, original and personal. Now, with Transubtil Records, Akhaba plays night psytrance : groovy, dark, and always introspective.', ARRAY['Dark-Prog', 'Psy Techno', 'Twilight', 'Darkpsy'], 'France', '/images/akhaba.jpg', '{"soundcloud": "https://soundcloud.com/akhaba", "instagram": "https://www.instagram.com/akhaba_kubba/", "facebook": "https://www.facebook.com/AkhabaSound"}', '{}'),

(8, 'Kanaloa', 'kanaloa', 'Dj Set / Live', 'Marcus is the DJ and Producer behind the psychedelic trance project Kanaloa. Kanaloa drives atmospheric and deep sounds, combining distorted textures with forest friendly elements and organic soundscapes, enveloping imagination into a fresh new style, connecting mind and body through unique sound storytelling.', ARRAY['Twilight', 'Forest', 'Darkpsy'], 'England', '/images/kanaloa.jpg', '{"soundcloud": "https://soundcloud.com/kanaloa_music", "instagram": "https://www.instagram.com/kanaloa_music", "facebook": "https://www.facebook.com/Kanaloa666"}', '{}'),

(9, 'Mekanorms', 'mekanorms', 'Dj Set', 'Originally from punk rock and hard rock, Mekanorms discovered the world of Psytrance in 2010. The seduction was immediate, the turntables attracted him instantly. That''s when he bought his first set-up and started mixing. He then had time to perfect himself and find his style that makes his DJ sets unique: groovy nightpsytrance with high-frequency mechanical sounds! He joined Transubtil Rec at the creation of the label and plays on dancefloors with international artists.', ARRAY['Twilight'], 'France', '/images/mekanorms.jpg', '{"soundcloud": "https://soundcloud.com/mekanorms", "instagram": "https://www.instagram.com/mekanorms_transubtilrecords/", "facebook": "https://soundcloud.com/mekanorms"}', '{}'),

(10, 'Jive', 'jive', 'Dj Set', 'Jive is the DJ project of Jai Royall from Australia. Representing Transubtil Records. Spawning in 2017, the project was developed as a tool to research and further understand the symbiosis between organic yet unearthly sonic textures and deep rhythmic structures. Jai is also the co-founder of the Murky Collective and the event director of the event Swampy Conscience which started in 2020.', ARRAY['Forest', 'Darkpsy'], 'Australia', '/images/jive.jpg', '{"soundcloud": "https://soundcloud.com/jivepsy", "instagram": "https://www.instagram.com/jairoyall?igsh=Nm5kZWprcWNqaXRw", "facebook": "https://www.facebook.com/share/18A2jTy5UN/"}', '{}'),

(11, 'Xipe Totecs', 'xipe-totecs', 'Live Act', 'Xipe Totecs is the Psytrance project from Japan, who started in 2018. They decided to keep exploring music from the rave scene, producing powerful sounds. Their universe encompasses epic themes and colorful frenzied drums, to create trance music full of new sonorities. They signed to the French label Transubtil Records in 2020.', ARRAY['Twilight'], 'Japan', '/images/xipetotecs.jpg', '{"soundcloud": "https://soundcloud.com/xipetotecs", "instagram": "https://www.instagram.com/xipe_totecs", "facebook": "https://www.facebook.com/Xipetotecs"}', '{}'),

(12, 'Dj Lazzy', 'dj-lazzy', 'Dj Set', '', ARRAY['Twilight'], 'Japan', '/images/djlazzzy.jpg', '{"instagram": "https://www.instagram.com/showurata_dj_lazzzy/"}', '{}'),

(13, 'Pakkun', 'pakkun', 'Dj Set', 'Pakkun alias Vincent has always been passionate about music, playing drums and bass guitar at a young age. Discovering electronic music through techno and d''n''b, he soon became in love with Psytrance. Learning the art of djing with the Transubtil crew led him to integrate the label at the end of 2019 and play in Japan in summer 2022. Constantly evolving, his sets range from groovy psytrance to darkpsy. Now working a lot on the production side, he''s eager to show you his own vision of psytrance on his first releases. He released his first compilation ''Chaos Simulator'' containing his first release with Dr Fractal, more coming this year.', ARRAY['Forest', 'Darkpsy'], 'France', '/images/pakkun.jpg', '{"soundcloud": "https://soundcloud.com/pakkun-psy", "instagram": "https://www.instagram.com/vincspakkun"}', '{}'),

(14, 'Agop', 'agop', 'Dj Set', 'AGOP is a DJ, producer and sound engineer who grew up within alternative artistic communities and was exposed to electronic music from an early age. This environment sparked a lasting fascination for psychedelic sounds, leading him to start DJing as a teenager. His first steps behind the decks took place at private parties — a formative playground where he refined his technique and developed his connection with a passionate crowd. Today, his project explores the many facets of the psytrance spectrum, blending groove, energy and hypnotic atmospheres. As a professional sound technician, he also holds a strong interest in the technical side of music, working on live sound for bands as well as several electronic and psytrance festivals. In 2025, he played at Hadra Trance Festival and joined Transubtil Records.', ARRAY['Twilight', 'Forest'], 'France', '/images/agop.jpg', '{"soundcloud": "https://soundcloud.com/agop_psychedelic", "instagram": "https://www.instagram.com/agop_transubtil", "facebook": "https://www.facebook.com/profile.php?id=100092196862973"}', '{}'),

(15, 'Fiorenza', 'fiorenza', 'Dj Set', 'Integrating the feminine underground scene of the Cerrado, Fiorenza transforms nocturnal sound into a powerful expression of feeling. Moving between 155 and 170 BPM, her sets traverse the textures of Forest and Dark, crafting a psychedelic sonic journey with heavy basslines and immersive atmospheres.', ARRAY['Forest', 'Darkpsy'], 'Brazil', '/images/fiorenza.jpg', '{"soundcloud": "https://soundcloud.com/fiorenzadj", "instagram": "https://www.instagram.com/fiorenzacadore/", "facebook": "https://www.facebook.com/fiorenzacadore"}', '{}'),

(16, 'Heavy Fawn', 'heavy-fawn', 'Dj Set', 'Heavy Fawn is the Nightpsy DJ project of Hugo, originally from Marseille, France. He discovered the world of psytrance and free parties in 2009, where he instantly fell in love with the music. In 2017, he met Tantra Music, began collaborating with them as a DJ and organizer, and together they made some of the best darkpsy festivals in southern France. In 2020, he joined the French label Transubtil Records and played in Mexico and Costa Rica. He later joined the Brazilian label Resina Records in 2024, from which he had drawn major inspiration for years. His first VA is set to be released in early 2026, a collaboration between Resina and Transubtil Records featuring only exclusive tracks. His goal is to create DJ sets that are neither forest, nor dark, nor twilight, nor hightech, but a perfect blend that is purely psychedelic.', ARRAY['Darkpsy', 'Forest', 'Twilight'], 'France', '/images/heavyfawn.jpg', '{"soundcloud": "https://soundcloud.com/heavyfawn", "instagram": "https://www.instagram.com/heavy_fawn/", "facebook": "https://www.facebook.com/HeavyFawn/"}', '{}'),

(17, 'Rajax', 'rajax', 'Dj Set', 'Since 2013, William really dived into the psytrance world, quickly a passion borned and his project RAJAX was born. His debut on stage was in 2015 with the Outrance association. In 2017, he joined the Senoï Project association, In March 2019, supported by this association, he launched his first compilation titled ''GENOME''. In 2023, he joined the growing label Transubtil Records, and starts delivering darker and faster DJ sets, yet his love for the groove remains intact. Each of his performances is unique and makes a strong impact on the dancefloors, confirming his place in the psytrance scene and creating unforgettable moments for the audience.', ARRAY['Darkpsy', 'Twilight'], 'France', '/images/rajax.jpg', '{"soundcloud": "https://soundcloud.com/rajax-outrance", "instagram": "https://www.instagram.com/rajax_outrance", "facebook": "https://www.facebook.com/Rajaxsenoi"}', '{}'),

(18, 'Wild Track', 'wild-track', 'Dj Set', 'Wild Track is a Moroccan DJ, formerly known as DJ Gender Fluid. He is always crafting tailored DJ sets based on the vibe of the dancefloor, staying fully tuned in to its energy. Groovy and psychedelic, his mixes become the ideal soundtrack for active meditation, trance, and free-form dance. Immersed in the global psytrance scene as a festival traveler and party organizer long before stepping behind the decks, he developed an endless curiosity for digging the most powerful, groovy, and mind-shifting tracks. His mission: channel that same magic he once felt in the crowd and deliver it back to the dancefloor. Deeply engaged in music, he is also the founder of Yaz Records and Universitek, an educational organization dedicated to sharing knowledge and nurturing creativity within the musical community.', ARRAY['Twilight', 'Forest'], 'Morocco', '/images/wildtrack.jpeg', '{"soundcloud": "https://soundcloud.com/wild_track", "instagram": "https://www.instagram.com/dj.wildtrack/"}', '{}'),

(19, 'Yagsa', 'yagsa', 'Dj Set', 'Yagsa started mixing in 2010 after his discovery of trance in Hadra Festival. In 2014 he joined the Transubil association and started performing in big dancefloors. Now in the Transubtil Records Label, he released a compilation in collaboration with Mekanorms ''Transsiberian''. Come and discover his universe with forest and psychedelic atmospheres.', ARRAY['Forest', 'Twilight'], 'France', '/images/yagsa.jpg', '{"soundcloud": "https://soundcloud.com/yagsa"}', '{}'),

(20, 'Anachronorium', 'anachronorium', 'Live Act', 'Anchronorium is the DarkPsy project of Portuguese producer Rafyx, exploring high-intensity soundscapes built on dissonant textures, immersive atmospheres, and fast, driving rhythms. His music blends detailed sound design with a cinematic sense of darkness, creating deep mental journeys and powerful nighttime energy on the dancefloor. With a signature style marked by high BPMs, hypnotic storytelling and dense psychedelic layers, Anchronorium delivers a modern and impactful interpretation of the dark psychedelic spectrum. The project continues to evolve with new releases and performances, establishing a strong and distinctive presence within contemporary DarkPsy.', ARRAY['Darkpsy', 'Hitech'], 'Portugal', '/images/anachronorium.jpg', '{}', '{}'),

(21, 'Veheme', 'veheme', 'Live Act', '', ARRAY['Darkpsy'], 'France', '/images/placeholder.webp', '{"soundcloud": "https://soundcloud.com/veheme"}', '{}'),

(22, 'Warp Drive', 'warp-drive', 'Live Act', 'Tim aka Warp Drive is a psytrance project hailing from the sunny shores of Sydney, Australia. Bootstrapped in the late 2010''s following many sleepless nights in the woods, it is a mince of cultural influences packed into a night psy skin. Bon appétit!', ARRAY['Twilight', 'Darkpsy'], 'Australia', '/images/warpdrive.jpg', '{"soundcloud": "https://soundcloud.com/transubtil", "instagram": "https://www.instagram.com/engagethewarpdrive/", "facebook": "https://www.facebook.com/Transubtilrec"}', '{}'),

(23, 'Zeo', 'zeo', 'Live Set', 'Candice aka Zeo started mixing Pystrance in 2016. Reasoning influences Dark, Forest but also very Groovy. It was in 2018 that she embarked on music production. Keeping the aim of making his audience travel through his emotions, his influences and his musical perception. What she likes about this style is its side, both dark but colorful, hypnotic, absorbing but also very energetic. That we can live introspectively or on the contrary, hyper communicative and synergistic. After a few years of preparation for her Live, today she is finally ready to reveal the plots of her little universe.', ARRAY['Darkpsy', 'Forest'], 'France', '/images/zeo.jpg', '{"soundcloud": "https://soundcloud.com/zeopsyrecord", "instagram": "https://www.instagram.com/zeo_zeeoo/", "facebook": "https://www.facebook.com/zeo.psyrec/"}', '{}');

-- Reset sequence to continue after last ID
SELECT setval('artists_id_seq', (SELECT MAX(id) FROM artists));

-- =============================================
-- SEED RELEASES DATA
-- =============================================
INSERT INTO releases (id, title, artist, type, release_date, catalog_number, cover_url, bandcamp_url, bandcamp_id, description, tracklist) VALUES
(1, 'V.A Nightmare Cage', 'Various Artists', 'compilation', '2025', '', 'https://f4.bcbits.com/img/a3318491286_10.jpg', 'https://transubtilrec.bandcamp.com/album/v-a-nightmare-cage', '1276691280', '', '{}'),
(2, 'Anchronorium - Paradoxal Ep', 'Anchronorium', 'ep', '2025', '', 'https://f4.bcbits.com/img/a2416868371_10.jpg', 'https://transubtilrec.bandcamp.com/album/anchronorium-paradoxal-ep', '4158104841', '', '{}'),
(3, 'Anchronorium - Dissonus', 'Anchronorium', 'track', '2025', '', 'https://f4.bcbits.com/img/a4182568214_10.jpg', 'https://transubtilrec.bandcamp.com/track/anchronorium-dissonus', '2775504586', '', '{}'),
(4, 'V.A Chaos Simulator', 'Various Artists', 'compilation', '2025', '', 'https://f4.bcbits.com/img/a1379365463_10.jpg', 'https://transubtilrec.bandcamp.com/album/v-a-chaos-simulator', '155406373', '', '{}'),
(5, 'Creepy Deep & Karev - Tongue Twister', 'Creepy Deep & Karev', 'ep', '2025', '', 'https://f4.bcbits.com/img/a0525244640_10.jpg', 'https://transubtilrec.bandcamp.com/album/creepy-deep-karev-tongue-twister', '3369648476', '', '{}'),
(6, 'Kanaloa - Obsidian', 'Kanaloa', 'ep', '2025', '', 'https://f4.bcbits.com/img/a2935245080_10.jpg', 'https://transubtilrec.bandcamp.com/album/kanaloa-obsidian', '452095018', '', '{}'),
(7, 'Best of 7 years', 'Various Artists', 'compilation', '2025', '', 'https://f4.bcbits.com/img/a1189286876_10.jpg', 'https://transubtilrec.bandcamp.com/album/best-of-7-years', '3676051951', '', '{}'),
(8, 'Opsuruus - No Humans', 'Opsuruus', 'track', '2025', '', 'https://f4.bcbits.com/img/a4025739748_10.jpg', 'https://transubtilrec.bandcamp.com/track/opsuruus-no-humans', '307314221', '', '{}'),
(9, 'V.A Ultra Heaven', 'Various Artists', 'compilation', '2025', '', 'https://f4.bcbits.com/img/a4033780181_10.jpg', 'https://transubtilrec.bandcamp.com/album/v-a-ultra-heaven', '3402257404', '', '{}'),
(10, 'Ingenious Brain - Brain Terms', 'Ingenious Brain', 'album', '2025', '', 'https://f4.bcbits.com/img/a0590020046_10.jpg', 'https://transubtilrec.bandcamp.com/album/ingenious-brain-brain-terms', '1106676205', '', '{}'),
(11, 'Zeo - Whispers Of Chaos', 'ZEO', 'album', '2024', '', 'https://f4.bcbits.com/img/a0100927535_10.jpg', 'https://transubtilrec.bandcamp.com/album/zeo-whispers-of-chaos', '2879833548', '', '{}'),
(12, 'Xipe Totecs - Party Games', 'Xipe Totecs', 'album', '2024', '', 'https://f4.bcbits.com/img/a3435246575_10.jpg', 'https://transubtilrec.bandcamp.com/album/xipe-totecs-party-games', '120594099', '', '{}'),
(13, 'Opsuruus - Surreal Contrast', 'Opsuruus', 'album', '2024', '', 'https://f4.bcbits.com/img/a1906946585_10.jpg', 'https://transubtilrec.bandcamp.com/album/opsuruus-surreal-contrast', '3318037261', '', '{}'),
(14, 'Warp Drive - Jungle Worms', 'Warp Drive', 'album', '2024', '', 'https://f4.bcbits.com/img/a2011308006_10.jpg', 'https://transubtilrec.bandcamp.com/album/warp-drive-jungle-worms', '3401677597', '', '{}'),
(15, 'Ingenious Brain - Dirty Experiments 2.0', 'Ingenious Brain', 'album', '2024', '', 'https://f4.bcbits.com/img/a2179041807_10.jpg', 'https://transubtilrec.bandcamp.com/album/ingenious-brain-dirty-experiments-20', '2293845675', '', '{}'),
(16, 'The Horrids - BioHackers', 'The Horrids', 'album', '2024', '', 'https://f4.bcbits.com/img/a1703897934_10.jpg', 'https://transubtilrec.bandcamp.com/album/the-horrids-biohackers', '1823970644', '', '{}'),
(17, 'Ingenious Brain - Dirty Experiments', 'Ingenious Brain', 'album', '2023', '', 'https://f4.bcbits.com/img/a1603163706_10.jpg', 'https://transubtilrec.bandcamp.com/album/ingenious-brain-dirty-experiments', '1760532212', '', '{}'),
(18, 'Dr Fractal - Red Spicy', 'Dr Fractal', 'ep', '2023', '', 'https://f4.bcbits.com/img/a3628587435_10.jpg', 'https://transubtilrec.bandcamp.com/album/dr-fractal-red-spicy', '6011190', '', '{}'),
(19, 'Strange Creatures Collective', 'Various Artists', 'ep', '2023', '', 'https://f4.bcbits.com/img/a4187356236_10.jpg', 'https://transubtilrec.bandcamp.com/album/strange-creatures-collective', '3468402328', '', '{}'),
(20, 'V.A Divergent Polarity', 'Various Artists', 'compilation', '2023', '', 'https://f4.bcbits.com/img/a3806326053_10.jpg', 'https://transubtilrec.bandcamp.com/album/v-a-divergent-polarity', '2123996018', '', '{}'),
(21, 'Precisely Nowhere', 'La Marquise', 'ep', '2023', '', 'https://f4.bcbits.com/img/a1853967297_10.jpg', 'https://transubtilrec.bandcamp.com/album/precisely-nowhere', '1918549876', '', '{}'),
(22, 'V.A Ta-Na-tsiic', 'Various Artists', 'compilation', '2022', '', 'https://f4.bcbits.com/img/a2987733204_10.jpg', 'https://transubtilrec.bandcamp.com/album/v-a-ta-na-tsiic', '1576423401', '', '{}'),
(23, 'Xipe Totecs - Evil in the shell - EP', 'Xipe Totecs', 'ep', '2022', '', 'https://f4.bcbits.com/img/a3428266115_10.jpg', 'https://transubtilrec.bandcamp.com/album/xipe-totecs-evil-in-the-shell-ep', '3535232346', '', '{}'),
(24, 'Dr Fractal - Into Matter', 'Dr Fractal', 'ep', '2022', '', 'https://f4.bcbits.com/img/a3563280128_10.jpg', 'https://transubtilrec.bandcamp.com/album/dr-fractal-into-matter', '2062036570', '', '{}'),
(25, 'V.A Freaky Riders', 'Various Artists', 'compilation', '2021', '', 'https://f4.bcbits.com/img/a1190837326_10.jpg', 'https://transubtilrec.bandcamp.com/album/v-a-freaky-riders', '1863032189', '', '{}'),
(26, 'Veheme - Subtil Cruizer', 'Veheme', 'ep', '2021', '', 'https://f4.bcbits.com/img/a0514647351_10.jpg', 'https://transubtilrec.bandcamp.com/album/veheme-subtil-cruizer', '3482061100', '', '{}'),
(27, 'Dr Fractal - Smooth Lobotomy', 'Dr Fractal', 'album', '2021', '', 'https://f4.bcbits.com/img/a1396341222_10.jpg', 'https://transubtilrec.bandcamp.com/album/dr-fractal-smooth-lobotomy', '832945600', '', '{}'),
(28, 'Paranoid Ep', 'The Horrids', 'ep', '2020', '', 'https://f4.bcbits.com/img/a2728262781_10.jpg', 'https://transubtilrec.bandcamp.com/album/paranoid-ep', '3496769874', '', '{}'),
(29, 'V.A New Wave Killer', 'Various Artists', 'compilation', '2020', '', 'https://f4.bcbits.com/img/a1575328914_10.jpg', 'https://transubtilrec.bandcamp.com/album/v-a-new-wave-killer', '3965082094', '', '{}'),
(30, 'Unsinkable Ep', 'Breaking Noise', 'ep', '2020', '', 'https://f4.bcbits.com/img/a0914071376_10.jpg', 'https://transubtilrec.bandcamp.com/album/unsinkable-ep', '3420337027', '', '{}'),
(31, 'Don Piano', 'Various Artists', 'album', '2020', '', 'https://f4.bcbits.com/img/a0745769195_10.jpg', 'https://transubtilrec.bandcamp.com/album/don-piano', '17496551', '', '{}'),
(32, 'Galaktic Garbage Ep', 'The horrids', 'ep', '2019', '', 'https://f4.bcbits.com/img/a0315600580_10.jpg', 'https://transubtilrec.bandcamp.com/album/galaktic-garbage-ep', '1913421101', '', '{}'),
(33, 'Andromed - In Loading Ep', 'Andromed', 'ep', '2019', '', 'https://f4.bcbits.com/img/a3097822958_10.jpg', 'https://transubtilrec.bandcamp.com/album/andromed-in-loading-ep', '1085913171', '', '{}'),
(34, 'Transsiberian', 'Various Artists', 'compilation', '2019', '', 'https://f4.bcbits.com/img/a2715032485_10.jpg', 'https://transubtilrec.bandcamp.com/album/transsiberian', '985067329', '', '{}'),
(35, 'Midnight snacks', 'Veheme', 'ep', '2019', '', 'https://f4.bcbits.com/img/a1453851969_10.jpg', 'https://transubtilrec.bandcamp.com/album/midnight-snacks', '1502904550', '', '{}'),
(36, 'South Syndicate', 'Various Artists', 'compilation', '2018', '', 'https://f4.bcbits.com/img/a0283231353_10.jpg', 'https://transubtilrec.bandcamp.com/album/south-syndicate', '3624884228', '', '{}'),
(37, 'Shrezonant', 'Shred''er & Rezonant', 'album', '2018', '', 'https://f4.bcbits.com/img/a1163501488_10.jpg', 'https://transubtilrec.bandcamp.com/album/shrezonant', '4078066189', '', '{}');

-- Reset sequence to continue after last ID
SELECT setval('releases_id_seq', (SELECT MAX(id) FROM releases));
